// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.remcarpediem.feignprotobuf.proto.dto;

public interface RegisterFormOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.remcarpediem.feignprotobuf.proto.dto.RegisterForm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>optional string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>optional string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string desc = 4;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>optional string desc = 4;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
