// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.remcarpediem.feignprotobuf.proto.dto;

public interface UserDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.remcarpediem.feignprotobuf.proto.dto.UserDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string url = 3;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>optional string url = 3;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
