// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.remcarpediem.feignprotobuf.proto.dto;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_RegisterForm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_remcarpediem_feignprotobuf_proto_dto_RegisterForm_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_UserDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_remcarpediem_feignprotobuf_proto_dto_UserDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022(com.remcarpediem.feignprot" +
      "obuf.proto.dto\"K\n\014RegisterForm\022\014\n\004name\030\001" +
      " \001(\t\022\020\n\010password\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\014\n" +
      "\004desc\030\004 \001(\t\"0\n\007UserDTO\022\n\n\002id\030\001 \001(\005\022\014\n\004na" +
      "me\030\002 \001(\t\022\013\n\003url\030\003 \001(\tB,\n(com.remcarpedie" +
      "m.feignprotobuf.proto.dtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_RegisterForm_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_RegisterForm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_remcarpediem_feignprotobuf_proto_dto_RegisterForm_descriptor,
        new java.lang.String[] { "Name", "Password", "Email", "Desc", });
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_UserDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_remcarpediem_feignprotobuf_proto_dto_UserDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_remcarpediem_feignprotobuf_proto_dto_UserDTO_descriptor,
        new java.lang.String[] { "Id", "Name", "Url", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
